clinical_trials_etl:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') | default('ACCOUNTADMIN', true) }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') | default('CLINICAL_TRIALS_DEV', true) }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') | default('COMPUTE_WH', true) }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | default('RAW_DATA', true) }}"
      threads: 4
      client_session_keep_alive: true
      query_tag: dbt_clinical_trials
    
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') | default('ACCOUNTADMIN', true) }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') | default('CLINICAL_TRIALS', true) }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') | default('COMPUTE_WH', true) }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | default('RAW_DATA', true) }}"
      threads: 8
      client_session_keep_alive: true
      query_tag: dbt_clinical_trials_prod