version: 2

models:
  - name: dim_trials
    description: Dimension table for clinical trials
    columns:
      - name: trial_key
        description: Surrogate key for the trial
        tests:
          - not_null
          - unique
      - name: nct_id
        description: Clinical trial identifier
        tests:
          - not_null
          - unique

  - name: fact_trial_metrics
    description: Fact table with trial metrics and measures
    columns:
      - name: trial_key
        description: Foreign key to dim_trials
        tests:
          - not_null
          - relationships:
              to: ref('dim_trials')
              field: trial_key

  - name: mart_monthly_summary
    description: Monthly summary of clinical trials activity
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
          max_value: 1000

  - name: mart_therapeutic_area_analysis
    description: Analysis by therapeutic area
    columns:
      - name: therapeutic_area
        description: Therapeutic area category
        tests:
          - not_null

  - name: mart_sponsor_analysis
    description: Analysis by sponsor
    columns:
      - name: sponsor_name_clean
        description: Cleaned sponsor name
        tests:
          - not_null

  - name: mart_geographic_analysis
    description: Geographic analysis of trials
    columns:
      - name: location_country_clean
        description: Country where trial is conducted
        tests:
          - not_null