version: 2

models:
  - name: stg_ctgov_studies
    description: "Staging table for clinical trials studies from CTGov API"
    columns:
      - name: nct_id
        description: "Unique ID of the clinical trial study"
      - name: brief_title
        description: "Phase of the study (e.g., Phase 2, Phase 3)"
      - name: official_title
        description: "Title of the study"
